    .no $0B90

; PC_MAIN   .eq	$3
R_SET_COLOR_PTR  .eq $F

SET_COLOR_ENTRY
    LDI $D0
    PHI R_SET_COLOR_PTR
    LDI $FF
    PLO R_SET_COLOR_PTR
    SEX R_SET_COLOR_PTR
SET_COLOR_LOOP0
    LDI $04

    STXD
    GLO R_SET_COLOR_PTR
    XRI $8F
    BNZ SET_COLOR_LOOP0
SET_COLOR_LOOP1
    LDI $07
    STXD
    GLO R_SET_COLOR_PTR
    XRI $5F
    BNZ SET_COLOR_LOOP1
SET_COLOR_LOOP2
    LDI $06
    STXD
    GLO R_SET_COLOR_PTR
    XRI $27
    BNZ SET_COLOR_LOOP2
SET_COLOR_LOOP3
    LDI $01
    STXD
    GLO R_SET_COLOR_PTR
    XRI $17
    BNZ SET_COLOR_LOOP3
SET_COLOR_LOOP4
    LDI $04
    STXD
    GLO R_SET_COLOR_PTR
    XRI $FF
    BNZ SET_COLOR_LOOP4

    INC R_SET_COLOR_PTR
    LDI $F3
    PLO R_SET_COLOR_PTR
    LDI $01
    STR R_SET_COLOR_PTR
    INC R_SET_COLOR_PTR
    STR R_SET_COLOR_PTR
    LDI $FB
    PLO R_SET_COLOR_PTR
    LDI $01
    STR R_SET_COLOR_PTR
    INC R_SET_COLOR_PTR
    STR R_SET_COLOR_PTR
    SEP PC_MAIN
