	.no $0300
; STACK			.eq $2
; PC_MAIN 		.eq	$3
; R_CUR_PAGE	.eq	$6
; R_VAR_PTR     .eq $8      ; Upper byte = $0D 
; R_TABLE_PTR   .eq $A

R_BLDG_DRAW_CNT .eq $D
R_BLDG_CNT		.eq	$E  ; lower
R_BLDG_X        .eq $E  ; upper
R_BLDG_DRAW_PTR	.eq	$F

DRAW_BUILDINGS
	GHI R_CUR_PAGE
	PHI R_BLDG_DRAW_PTR
	LDI /BITPAT_DOT
	PHI R_TABLE_PTR
    LDI $03
    PLO R_BLDG_CNT

    SEX R_VAR_PTR
    LDI #V_DIR_CAR
    PLO R_VAR_PTR
    SEX R_VAR_PTR
    SM
    PHI R_BLDG_X
DRAW_BUILDINGS_L0
    LDI $88
	PLO R_BLDG_DRAW_PTR
    GHI R_BLDG_X
    ANI $3F
	SHR
	SHR
	SHR
	SEX STACK
	STR STACK
	GLO R_BLDG_DRAW_PTR
	ADD
	PLO R_BLDG_DRAW_PTR
    GHI R_BLDG_X
    ANI $07
	ADI #BITPAT_DOT
	PLO R_TABLE_PTR

    GLO R_BLDG_CNT
    ADI $01
    PLO R_BLDG_DRAW_CNT
DRAW_BUILDINGS_L1
	LDN R_TABLE_PTR
	STR R_BLDG_DRAW_PTR
    GLO R_BLDG_DRAW_PTR
    SMI $08
    PLO R_BLDG_DRAW_PTR
    DEC R_BLDG_DRAW_CNT
    GLO R_BLDG_DRAW_CNT
    BNZ DRAW_BUILDINGS_L1
DRAW_BUILDING_FINAL
    DEC R_BLDG_CNT
    GLO R_BLDG_CNT
	BZ DRAW_BUILDINGS_EXIT
    GHI R_BLDG_X
	ADI $17
    PHI R_BLDG_X
	BR DRAW_BUILDINGS_L0
DRAW_BUILDINGS_EXIT
	SEP PC_MAIN

